http:
  timeout: 10s
  idleTimeout: 60s
  host: "localhost"
  port: 9090

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  driver: "postgres"
  password: "qwerty"
  dbName: "postgres"
  dbIdleTimeout: 30
